faq/index.html.tt2

According to the [release notes of 2017.05](https://grml.org/changelogs/README-grml-2017.05/), the new baseline is the i686.

Update requirements to reflect release 2017.05

---

zsh/index.html.tt2

Thanks to NobbZ for the reporting the broken link.
Closes grml/grml.org#19

Fix dead link of grml-zsh-config package for Archlinux

---

files/index.html.tt2

this change allows people to setup the Grml repositories without trusting them with base packages and will enforce the signature on the repository as well instead of trusting the upstream `grml-debian-archive` package which could be hijacked.
it also adds a preferences sample file and a way to install the keyring without downloading the package, which fails on stretch.

debian repository instructions improvements

---

files/index.html.tt2

The [repository instructions](https://wiki.debian.org/RepositoryInstructions) have been changed to avoid writing third-party keyring files to the global trust anchors (in `/etc/apt/trusted-gpg.d`) and instead write those to a more neutral location (`/usr/share/keyrings`, alongside other keyring files).
The downside of this change is that the key fingerprint isn't validated directly through this process. But considering that validation of the key is anchored through HTTPS validation in the first place, we do not *really* lose anything by moving that to the `.gpg` file transfer: that file's integrity is still checked through HTTPS. Furthermore, not storing the explicit fingerprint here will make future key rotations easier as they will not require documentation updates.
Note that this …

pull archive keyring out of global trust path

---

faq/index.html.tt2

The location of the official Linux kernel documentation has changed.
Mentioned in: grml/grml#22

Update link to Linux kernel command-line parameters

---

faq/index.html.tt2

a Gnackwatschn isn't the same as facepalm. especially as it is not self-inflicted.

faq: Gnackwatschn is not a facepalm

---

changelogs/README-grml-2020.06-rc1/index.html.tt2

The (list) items of the (highlighted) "New features" were too tiny.
The second level of the unordered list made the fonts so small.
Changed the first level of the unordered list to a (level 4) heading but
did not change the indentation of the (former) second level of the
unordered list to avoid touching too much lines.
While at it also fixed a closing tag of an unordered list.
@mika I have no build environment at hand to test "real" output, but the raw HTML output looked fine. What do you think?

Update grml-2020.06-rc1 release notes

---

download/index.html.tt2

This is easier to copy-paste:
```
dd bs=4M status=progress conv=fdatasync if=grml_2021.07.iso of=/dev/USB_KEY
```
... because I can just paste it in a terminal and all I have to change is the last word. Compare with the previous version:
```
dd if=grml_2021.07.iso of=/dev/USB_KEY bs=4M status=progress conv=fdatasync
```
... where you have to paste, move your cursor right before ` bs` (notice the space), then change the word.
All that `bs=` and `conv=` is cosmetic anyways, keep the good stuff where it matters, near the end of line, where the cursor will be.

reverse the order of dd arguments to ease copy

---

scripts/grml-config.sh

On e.g. OS X wget isn't available but curl is, so check wget is available, else try curl or otherwise report error.
While at it, fail early and on any error.
See updated version of
https://michael-prokop.at/blog/2007/12/22/make-console-work-comfortable/

scripts/grml-config.sh: check whether wget and/or curl are available and fail on errors

---

team/index.html.tt2

Thank you for all your support over the many years. We haven't received any contributions from you for a long time and are now setting your status to Alumni.
If you would like to actively contribute again, please reach out! :)
Thanks for everything!

team: move Alexander 'formorer' Wirt from Active to Alumni

---

daily/index.html

The new variants use a temporary name until we redo all the names.

Update /daily/ for new builds

---

console/.htaccess

Can be used on https://michael-prokop.at/blog/2007/12/22/make-console-work-comfortable/ instead of linking to http://git.grml.org/f/grml-etc-core/etc/skel/.zshrc directly.

console: add redirect for zshrc.local

---

download/prerelease/index.html.tt2

It is likely we will release only two arch flavours, and no combined ISO. Thus, drop the links for grml96.
As this now allows to use radio buttons again - which are advantageous because they present the possible options without having to click - let's use them.

download/prerelease: drop grml96, switch to radios

---

content/changelogs/_index.md

changelogs: reword list of all Grml releases
Currently it reads:
```
Current release
Release announcement for Grml 2024.12 - codename Adventgrenze
Previous releases
* Grml 2024.12 - codename Adventgrenze
* Grml 2024.02 - codename Glumpad
* Grml 2022.11 - codename MalGuckes
* Grml 2021.07 - codename JauKerl
* Grml 2020.06 - codename Ausgehfuahangl
* Grml 2018.12 - codename Gnackwatschn
* Grml 2017.05 - codename Freedatensuppe
* Grml 2014.11 - codename Gschistigschasti
[...]
```
So the current version is listed twice, though getting rid of the current list in the list for "Previous releases" probably isn't worth it, given that it's actually nice to have a consistent list of all our releases in the same format/schema, e.g. for c/p. So reword `Previous releases` accordingly.

changelogs: reword list of all Grml releases

---

content/qemu/index.md

These examples come from my notes. I cannot verify the amd64 examples right now, so if someone else can that'd be nice.

qemu: add/update examples

---

content/qemu/index.md

I could have also closed the quotes, but the other examples here do not use quotes around `efi_vars.fd`.
While at it, I changed the path to the Grml ISO to the current path.
I don't like to assume that the ISO is located in $HOME.

qemu: Remove unclosed double quote around efi_vars.fd

---

content/team/index.md

It looks like I did a poor job with maintaining that list, but when researching the time since 2003, noticed we had further alumnis!

team: update list of alumni developers

---

content/files/_index.md

The directory is named /etc/apt/sources.list.d/, not /etc/apt/sources.list/.
Use file extension pgp instead of gpg, as recommended by current best practices and noticed as problem on Ubuntu 22.04.5 LTS/jammy, see https://github.com/grml/grml-keyring/issues/23 for details.
While at it, drop instructions for stretch + buster, we no longer test them, nor recommend their usage.

Package Repository instructions: fix sources.list usage, use pgp extension

---

content/tips/index.md

In grml/grml-tips#8 we made some adjustments to make grml-tips start the numbering with 1:
```
❯ grep -e "^-- " -A1 grml_tips | grep -v -- "^--" | cat -n | head
1  Configure network:
2  Deactivate error correction of zsh:
3  Disable automatic setting of title in GNU screen:
4  Do not use menu completion in zsh:
5  Run GNU screen with grml-configuration:
6  Print out grml-version:
7  Configure mutt:
8  Use encrypted files / partitions:
9  Change resolution of X:
10  Change resolution of framebuffer:
```
We missed to adjust our website: https://grml.org/tips started its numbering with 0.
Issue: grml/grml-tips#8

Make grml.org/tips start with 1

---

content/docs/index.md
content/faq/_index.md

grml-tips needs some love and are hard to find.
Added links to grml-tips in the documentation and faq page to create more visibilty.
Issue: grml/grml-tips#6

Add links to grml-tips in documentation and faq page
